export const items = [
  {
    id: '1',
    img: '/assets/paint-1.jpg',
    name: 'Краска Wallquest, Brownsone MS90102',
    price: 6000,
    popularity: 100,
    date: 429,
    features: {
      new: true,
      available: true,
      contract: false,
      exclusive: false,
      sale: false,
    },
  },
  {
    id: '2',
    img: '/assets/paint-2.jpg',
    name: 'Краска Wallquest, Brownsone MS90102',
    price: 4800,
    popularity: 100,
    date: 600,
    features: {
      new: true,
      available: true,
      contract: false,
      exclusive: false,
      sale: false,
    },
  },
  {
    id: '3',
    img: '/assets/paint-3.jpg',
    name: 'Краска Wallquest, Brownsone MS90102',
    price: 5290,
    popularity: 100,
    date: 1000,
    features: {
      new: true,
      available: true,
      contract: false,
      exclusive: true,
      sale: true,
    },
  },
  {
    id: '4',
    img: '/assets/paint-4.jpg',
    name: 'Краска Wallquest, Brownsone MS90102',
    price: 2800,
    popularity: 100,
    date: 13,
    features: {
      new: true,
      available: true,
      contract: false,
      exclusive: false,
      sale: true,
    },
  },
  {
    id: '5',
    img: '/assets/paint-5.jpg',
    name: 'Краска Wallquest, Brownsone MS90102',
    price: 2800,
    popularity: 100,
    date: 13,
    features: {
      new: true,
      available: true,
      contract: false,
      exclusive: false,
      sale: true,
    },
  },
  {
    id: '6',
    img: '/assets/paint-6.jpg',
    name: 'Краска Wallquest, Brownsone MS90102',
    price: 2800,
    popularity: 100,
    date: 13,
    features: {
      new: true,
      available: true,
      contract: false,
      exclusive: false,
      sale: true,
    },
  },
];
